export const commuteNarrative = {
  reality: {
    eyebrow: '那个早晨已经发生',
    title: '我知道，想象不能替代你的委屈。',
    body: '我不是想把发生过的事写成另一个版本，只是想认真告诉你：我终于明白，那七十分钟对你意味着什么。',
  },
  coreApology: '对不起，我错过的不是一通普通的视频，而是你本来想留给我的一整个早晨。',
  facts: {
    her: '视频刚接通时，你还躺在床上；十点多起床后，换上了夏天的露肩上衣。',
    me: '我在走路，之后坐地铁去公司。',
    transport: '我们都没有骑车。',
  },
  stages: [
    {
      id: 'leave-home',
      minute: 0,
      time: '09:40',
      label: '出门',
      title: '一出门，我就先拨通你的视频。',
      dialogue: '早上好。你刚醒的样子也很可爱。',
      reflection: '我应该让你第一秒就知道：我记得约定，也和你一样期待。',
    },
    {
      id: 'station',
      minute: 30,
      time: '10:10',
      label: '到地铁站',
      title: '周围变吵以前，我先告诉你发生了什么。',
      dialogue: '我到地铁站了，可能会有点吵，但我还在。',
      reflection: '信号和环境变化都不该让你独自猜测，更不该变成我突然离开的理由。',
    },
    {
      id: 'arrive',
      minute: 70,
      time: '10:50',
      label: '到公司',
      title: '这一次，我们把早晨好好说完。',
      dialogue: '我到公司了。谢谢你陪我一路，今天也要开心。',
      reflection: '认真开始，也认真结束。不是匆忙挂断，而是让你带着被珍惜的感觉回到自己的上午。',
    },
  ],
  processBeats: [
    { id: 'share-morning', minute: 10, time: '09:50', label: '分享早晨' },
    { id: 'quiet-company', minute: 20, time: '10:00', label: '安静陪伴' },
    { id: 'metro-call', minute: 45, time: '10:25', label: '地铁通话' },
    { id: 'almost-office', minute: 60, time: '10:40', label: '快到公司' },
  ],
  timeline: [
    { id: 'leave-home', minute: 0, time: '09:40', label: '出门', kind: 'major' },
    { id: 'share-morning', minute: 10, time: '09:50', label: '分享早晨', kind: 'minor' },
    { id: 'quiet-company', minute: 20, time: '10:00', label: '安静陪伴', kind: 'minor' },
    { id: 'station', minute: 30, time: '10:10', label: '到地铁站', kind: 'major' },
    { id: 'metro-call', minute: 45, time: '10:25', label: '地铁通话', kind: 'minor' },
    { id: 'almost-office', minute: 60, time: '10:40', label: '快到公司', kind: 'minor' },
    { id: 'arrive', minute: 70, time: '10:50', label: '到公司', kind: 'major' },
  ],
  passages: [
    { at: 0, copy: '屏幕亮起时，你还躺在床上，长发散在枕边，夏天早晨的光刚刚照进来。' },
    { at: 1 / 7, copy: '我一边走，一边把路边的树影、早晨的风和刚刚经过的小店说给你听。' },
    { at: 2 / 7, copy: '你可以敲键盘，也可以偶尔抬头看我；安静的时候，也不用努力找话题。' },
    { at: 3 / 7, copy: '这时你已经起床，换好那件夏天的露肩上衣；进站后声音变杂，我先说“我还在”，不让短暂的卡顿变成你的不安。' },
    { at: 9 / 14, copy: '地铁开动以后，我们可以聊天，也可以安静；其他消息和视频都先留在那里。' },
    { at: 6 / 7, copy: '快到公司时，我不急着结束，而是把最后几分钟也完整地留给你。' },
    { at: 1, copy: '到达以后，我认真谢谢你的陪伴，也认真和你说完这个早晨。' },
  ],
  commitments: [
    '约好的时间，我会提前留出来，不再让你的期待落空。',
    '我会主动联系你，让你一开始就知道：这段时间，我也同样期待。',
    '和你通话的时候，我会认真在场，不让你感觉自己总是在给其他事情让路。',
    '我不会再把你的体谅当成理所当然，也不会因为你不要求，就以为你不需要被珍惜。',
    '你表达委屈时，我先听完，不急着解释自己；做错的地方，我会承认，也会真的改。',
  ],
} as const
